### ISSUE TITLE
Startup BAT script shows so many debug

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#17]
Hi Eric!
This is Carlos SS testing your first version.   :-)

I've detected startup BAT script "start.bat" shows so many debug information (including SSH passwords).
Is possible:
- rename current "start.bat" to "start_debug.bat"
- create "start.bat" with this contents:
java -splash:icon/splash.jpg -jar SmartPutty.jar
?

This will give to SmartPutty a more professional image, without lots of debug.

Thanks!

**Comment by msmigiel** [comment]
If you open up SmartPutty.jar, you'll see a file called log4j.properties. If you change it as follows, you will no longer see the DEBUG statements.

Before: log4j.rootLogger=DEBUG, stdout, file
After: log4j.rootLogger=INFO, stdout, file

You can use a program like 7Zip or similar to open it up as an archive instead of as a Java executable. However, out of the box the logging should be set to INFO so there is a defect here to address.

**Comment by crisistotal2014** [comment]
Sure MsMigiel! But this should be a "clean" program for normal users. By this I did my proposal.

**Comment by ericmore** [comment]
Wow, you got the right thing, I recall that log4j level can  control
output. I will update it. Thanks.

2018-02-23 15:00 GMT+08:00 Carlos SS <notifications@github.com>:

**Comment by crisistotal2014** [comment]
Now debug level is "normal". We can close this.
